version: '3.8'

services:
  testing-database:
    container_name: testing-database
    hostname: testing-database
    build: ../database
    env_file: './.e2e.env'
    ports:
      - 5432:5432

  testing-service:
    container_name: testing-service
    hostname:  testing-service
    build:
      context: ../..
      dockerfile: docker/testing/Dockerfile
    volumes:
      - ../..:/app
      - '/app/node_modules'
    env_file: './.e2e.env'
    depends_on:
      - testing-database