version: '3.8'

services:
  database:
    container_name: database
    hostname: database
    build: ./database
    env_file: './.env'
    ports:
      - 5432:5432

  app:
    container_name: app
    hostname: app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: sh -c 'export $$(node ./dist/cli/printAwsSecrets.js | xargs -0); npm run start:debug'
    volumes:
      - ..:/app
      - '/app/node_modules'
    ports:
      - '3030:3030'
    env_file: './.env'
    depends_on:
      - database

